//Want to replace all survivor images with gif version for better transparency.

class Perk {
    constructor(title, image, desc) {
        this.title = title
        this.image = image
        this.desc = desc
    }
}
const aceInTheHole = new Perk("Ace in the Hole", "survivorimgs/AceInTheHole.gif", "When retrieving an Item from a Chest, there is a chance an Add-on will be attached to it. 100% chance for an Add-on of Very Rare Rarity or lower. 10/25/50 % chance for a second Add-on of Uncommon Rarity or lower. Ace in the Hole allows you to keep any Add-ons your Item has equipped upon escaping.")
const Adrenaline = new Perk("Adrenaline", "survivorimgs/Adrenaline.gif", "When the Exit Gates are powered, instantly heal one Health State and sprint at 150 % of your normal Running speed for 5 seconds. Adrenaline is on hold if you are disabled at the moment it triggers and will instead activate upon being freed. If playing against The Nightmare, Adrenaline will wake you from the Dream World upon activation. Adrenaline ignores an existing Exhaustion timer, but causes the Status Effect for 60/50/40 seconds.")
const Aftercare = new Perk("Aftercare", "survivorimgs/Aftercare.gif", "You see the Aura of the last 1/2/3 Survivor(s): You have rescued from a Hook, or who have rescued you from a Hook. You have completed a Healing action on, or who have completed a Healing action on you. They also see your Aura.All effects of Aftercare are reset upon being hooked by the Killer.")
const Alert = new Perk("Alert", "survivorimgs/Alert.gif", "Whenever the Killer destroys a Pallet or a Breakable Wall, or damages a Generator, their Aura is revealed to you for 3/4/5 seconds.")
const anyMeansNecessary = new Perk("Any Means Necessary", "survivorimgs/AnyMeansNecessary.gif", "You see the Auras of dropped Pallets. Press and hold the Active Ability button for 4 seconds while standing beside a dropped Pallet to reset it to its upright position. Any Means Necessary has a cool-down of 100/80/60 seconds.")
const Appraisal = new Perk("Appraisal", "survivorimgs/Appraisal.gif", "Start the Trial with 3 Tokens: When a Chest has already been opened, consume 1 Token to rummage through it for an Item. Rummage through Chests 40/60/80 % faster. Rummaging is only available once per Chest.")
const Autodidact = new Perk("Autodidact", "survivorimgs/Autodidact.gif", "You start the Trial with a -25 % Progression penalty for Skill Checks to heal Survivors. For every successful Skill Check completed while healing a Survivor, Autodidact gains 1 Token up to a maximum of 3/4/5 Tokens. Each Token grants a +15 % bonus Progression for a successful Skill Check while healing Survivors. Great Skill Checks cannot be performed while using Autodidact. Autodidact is not active when using a Med-Kit to heal.")
const Babysitter = new Perk("Babysitter", "survivorimgs/Babysitter.gif", "When you unhook a Survivor, the rescued Survivor will leave neither Scratch Marks nor Pools of Blood for the next 4/6/8 seconds. Both you and the Killer see each other's Aura for 4 seconds.")
const balancedLanding = new Perk("Balanced Landing", "survivorimgs/BalancedLanding.gif", "When falling from great heights: Your Stagger duration is reduced by 75 % and your grunts are muffled by 100 %. Upon landing, you start sprinting at 150 % of your normal running speed for a maxiumum of 3 seconds. Balanced Landing causes the Exhausted Status Effect for 60/50/40 seconds. Balanced Landing cannot be used when Exhausted.")
const situationalAwareness = new Perk("Situational Awareness", "survivorimgs/BetterTogether.gif", "While repairing a Generator, its Aura is revealed in yellow to all other Survivors located within 32 metres. If the Killer downs a Survivor while you are repairing a Generator, you see the Auras of all other Survivors for 8/9/10 seconds.")
const biteTheBullet = new Perk("Bite the Bullet", "survivorimgs/BiteTheBullet.gif", "When healing yourself or another Survivor, Grunts of Pain and all noises related to the Healing action are suppressed: Failed Healing Skill Checks do not trigger a Loud Noise Notification and only apply a Regression penalty of 3/2/1 %.")
const blastMine = new Perk("Blast Mine", "survivorimgs/BlastMine.gif","After repairing Generators for a total of 66 %, Blast Mine activates: After repairing a Generator for at least 3 seconds, press the Ability button to install a Trap, which stays active for 35/40/45 seconds. The Aura of Trapped Generators are revealed in yellow to all Survivors. When the Killer damages a Trapped Generator, the Trap explodes, stunning them and blinding anyone nearby. Blast Mine deactivates after triggering successfully.")
const bloodPact = new Perk("Blood Pact", "survivorimgs/BloodPact.gif","When you or the Obsession are injured, you both see each other's Auras. After healing the Obsession or being healed by the Obsession, you both gain the Haste Status Effect, moving at an increased speed of 5/6/7 % until you are no longer within 16 metres of each other. If you are the Obsession, Blood Pact deactivates. Increases the odds of being the Obsession by 100%. The Killer can only be obsessed with one Survivor at a time.")
const boilOver = new Perk("Boil Over", "survivorimgs/BoilOver.gif", "While being carried by the Killer: Your Struggle Effects from Wiggling, causing the Killer to strafe sideways, are increased by 25/50/75 %. You obscure the Killer's ability to read the Auras of all Hooks within 10/12/14 metres of your pick-up location.")
const Bond = new Perk("Bond", "survivorimgs/Bond.gif", "Unlocks potential in your Aura-reading ability. The Auras of other Survivors are revealed to you when they are within a range of 20/28/36 metres.")
const boonCircleofHealing = new Perk("Boon: Circle of Healing", "survivorimgs/BoonCircleOfHealing.gif", "Press and hold the Active Ability button near a Dull or Hex Totem to bless it and create a Boon Totem. Soft chimes ring out within a radius of 28 metres. Survivors inside the Boon Totem's range benefit from the following effects: 90/95/100 % bonus to all Healing Speeds. Unlocks the Self-Care ability, allowing to self-heal without needing a Med-Kit at 50 % of the normal Healing speed. Also benefits from the Healing Speed bonus, boosting the Self-Healing speed to 95/97.5/100 %.")
const boonShadowStep = new Perk("Boon: Shadow Step", "survivorimgs/BoonShadowStep.gif", "Press and hold the Active Ability button near a Dull or Hex Totem to bless it and create a Boon Totem. Soft chimes ring out within a radius of 28 metres. Survivors inside the Boon Totem's range benefit from the following effects: Scratch Marks are suppressed. Auras are hidden from The Killer. Both effects linger for 2/3/4 seconds after leaving the Boon Totem's range. You can only bless one Totem at a time. All equipped Boon Perks are active on the Same Boon Totem.")
const borrowedTime = new Perk("Borrowed Time", "survivorimgs/BorrowedTime.gif", "For 10/15/20 seconds after unhooking a Survivor, the unhooked Survivor is protected by the Endurance Status Effect. Any damage taken that would put the Survivor into the Dying State will instead trigger the Deep Wound Status Effect, after which the Survivor has 20 seconds to Mend themselves. Taking damage while under the effect of Deep Wound or if its timer runs out will put the Survivor into the Dying State.")
const botanyKnowledge = new Perk("Botany Knowledge", "survivorimgs/Teachable_botanyKnowledge.png", "Healing speeds, as well as the efficiency of Med-Kits, are increased by 11/22/33 %.")
const Breakdown = new Perk("Breakdown", "survivorimgs/Breakdown.gif", "Each time you are unhooked or unhook yourself, the Hook breaks and the Killer's Aura is revealed to you for 4/5/6 seconds. A Hook broken by Breakdown takes 180 seconds to respawn.")
const Breakout = new Perk("Breakout", "survivorimgs/Breakout.gif", "When within 6 metres of a carried Survivor, you gain the Haste Status Effect, moving at an increased speed of 5/6/7 %. The carried Survivor's Wiggling speed is increased by 20 %.")
const buckleUp = new Perk("Buckle Up","survivorimgs/BuckleUp.gif", "You can determine the Recovery progress of dying Survivors by the intensity of their Aura at a distance of 48 metres away. When healing another Survivor from the Dying State to the Injured State, the Killer's Aura is revealed to the both of you for 4/5/6 seconds.")
const builtToLast = new Perk("Built to Last", "survivorimgs/BuiltToLast.gif", "Hiding inside a Locker for 14/13/12 seconds while carrying a depleted Item will replenish its Charges to 99 %. Each use of Built to Last reduces this percentage by -33 %.")
const calmSpirit = new Perk("Calm Spirit", "survivorimgs/Teachable_calmSpirit.png", "The chances of alerting nearby Crows are reduced by 80/90/100 % and your urge to scream from pain is suppressed.")
const Clairvoyance = new Perk("Clairvoyance", "survivorimgs/Clairvoyance.gif", "Whenever you cleanse a Totem, Clairvoyance activates: When empty-handed, press and hold the Active Ability button to unlock your full Aura-reading potential, allowing you to see the Auras  of the Exit Gate Switches, Generators, Hooks, and Chests within 64 metres for 8/9/10 seconds.")
const Counterforce = new Perk("Counter Force", "survivorimgs/Counterforce.gif", "You cleanse Totems 20 % faster. Gain another, stack-able 20 % Cleansing Speed bonus per cleansed Totem. After cleansing a Totem, the Aura of the Totem farthest from you is revealed to you for 2/3/4 seconds.")
const danceWithMe = new Perk("Dance with Me", "survivorimgs/DanceWithMe.gif", "When performing a rushed action to vault a Window or leave a Locker, you will not leave any Scratch Marks for the next 3 seconds. Dance With Me has a cool-down of 60/50/40 seconds.")
const darkSense = new Perk("Dark Sense", "survivorimgs/DarkSense.gif", "Unlocks potential in your Aura-reading ability. Each time a Generator is completed, the Killer's Aura is revealed to you for 5 seconds and for 5/7/10 seconds when the last Generator is completed.")
const deadHard = new Perk("Dead Hard", "survivorimgs/DeadHard.gif", "When Injured, tap into your adrenaline bank and dash forward quickly to avoid damage. Press the Active Ability button while running to dash forward. Avoid any damage during the Dash. Dead Hard causes the Exhausted Status Effect for 60/50/40 seconds. Dead Hard cannot be used when Exhausted.")
const Deception = new Perk("Deception", "survivorimgs/Deception.gif", "Interact with a Locker while holding the Sprint button to trigger a Loud Noise Notification for the killer at your location instead of entering the Locker. You will not leave any Scratch Marks or Pools of Blood for the next 3 seconds Deception can only be triggered once every 60/50/40 seconds.")
const decisiveStrike = new Perk("Decisive Strike", "survivorimgs/DecisiveStrike.gif", "After being unhooked or unhooking yourself, Decisive Strike activates for the next 40/50/60 seconds: When being grabbed or picked up by the Killer, succeed a Skill Check to automatically escape their grasp, stunning them for 5 seconds. Successfuly stunning the Killer will disable Decisive Strike for the remainer of the Trial and result you in becoming the Obsession. While Decisive Strike is active, the following interactions will deactivate it: Repairing a Generator. Healing yourself or other Survivors. Cleansing or blessing a Totem. Sabotaging a Hook. Unhooking other Survivors. Increases the odds of being the Obsession by 100 %. The Killer can only be obsessed with one Survivor at a time.")
const Deliverance = new Perk("Deliverance", "survivorimgs/Deliverance.gif", "After performing a Safe Hook Rescue on another Survivor, Deliverance activates: Your Self-Unhook attempts will succeed 100 % of the time. Deliverance causes the Broken Status Effect for 100/80/60 seconds after unhooking yourself.")
const desperateMeasures = new Perk("Desperate Measures", "survivorimgs/DesperateMeasures.gif", "Increases Healing and Unhooking speeds by 10/12/14 % for each injured, hooked, or dying Survivor, up to a maximum of 40/48/56 %.")
const detectivesHunch = new Perk("Detectives Hunch", "survivorimgs/DetectivesHunch.gif", "Each time a Generator is completed, the Auras of any Generators, Chests, and Totems within 32/48/64 metres are revealed to you for 10 seconds. If you are holding a Map IconItems map.png, any objects revealed by Detective's Hunch will automatically be tracked by it.")
const Distortion = new Perk("Distortion", "survivorimgs/Distortion.gif", "You start the trial with 3 Tokens. Whenever the Killer attempts to read your Aura, Distortion activates and a Token is consumed: Your Aura will not be shown to the Killer and you will not leave any Scratch Marks for the next 6/8/10 seconds. Distortion does not activate when you are in the Dying State or in a Killer Trap.")
const Diversion = new Perk("Diversion", "survivorimgs/Diversion.gif", "Standing within the Killer's Terror Radius while not in a Chase for 40/35/30 seconds activates Diversion. Once Diversion is activated, press the Active Ability button while crouched and motionless to throw a pebble, creating a distraction for the Killer at a distance of 20 metres. The distraction consists of the following: A Loud Noise Notification Scratch Marks Diversion's timer resets once the ability has been activated.")
const dejaVu = new Perk("Deja Vu", "survivorimgs/DejaVu.gif", "Unlocks potential in your Aura-reading ability. Paranoia paired with your horror of failure helps prepare you from repeating the same mistakes. The Auras of 3 Generators in closest proximity to one another are revealed to you for 30/45/60 seconds at the start of the Trial, and each time a Generator is completed. If you are holding a Map, Generators revealed by Déjà Vu are automatically added to it.")
const Empathy = new Perk("Empathy", "survivorimgs/Empathy.gif", "The Auras of dying or injured Survivors are revealed to you within a range of 64/96/128 metres. Empathy does not reveal the Aura of a survivor currently being carried by the Killer.")
const fastTrack = new Perk("Fast Track", "survivorimgs/FastTrack.gif", "Whenever another Survivor is hooked, Fast Track gains 1/2/3 Tokens, up to a maximum of 9/18/27 Tokens. You consume all accumulated Tokens after a Great Skill Check on a Generator. Each Token grants a stack-able 1 % Progression bonus in addition to the defult Progression bonus for succeeding a Great Skill Check.")
const selfAware = new Perk("Self-Aware", "survivorimgs/Fixated.gif", "You walk 10/15/20 % faster and can see your own Scratch Marks.")
const Flashbang = new Perk("Flashbang", "survivorimgs/Flashbang.gif", "After repairing Generators for a total of 70/60/50 %, Flashbang activates: Enter a Locker while empty-handed and press the Ability button to craft a Flash Grenade.")
const flipFlop = new Perk("Flip-Flop", "survivorimgs/Flip-Flop.gif", "While in the Dying State, 50 % of your Recovery progression is converted into Wiggling progression, up to a maximum of 40/45/50 %, once you are picked up by the Killer.")
const forThePeople = new Perk("For The People", "survivorimgs/ForThePeople.gif", "For the People is only active while at full health. Press the Active Ability button while healing another Survivor without a Med-Kit to instantly heal them 1 Health State. You become the Obsession. For the People causes the Broken Status Effect for 80/70/60 seconds after using it.")
const Guardian = new Perk("Guardian", "survivorimgs/Guardian.gif", "When you unhook a Survivor, the rescued Survivor benefits from the following effects for 4/6/8 seconds: Scratch Marks and Pools of Blood are suppressed. 7 % Haste Status Effect, boosting their Movement speed. Guardian reveals the Killer's Aura to you for 8 seconds.")
const headOn = new Perk("Head On", "survivorimgs/HeadOn.gif", "While standing in a Locker for 3 seconds, Head On activates: When performing a rushed action to leave a Locker, stun the Killer for 3 seconds if they are within range. Head On causes the Exhausted Status Effect for 60/50/40 seconds. Head On cannot be used when Exhausted or when you have accrued Stillness Crows.")
const Hope = new Perk("Hope", "survivorimgs/Hope.gif", "As soon as the Exit Gates are powered, you gain a 5/6/7 % Haste Status Effect for 120 seconds.")
const innerHealing = new Perk("Inner Healing", "survivorimgs/InnerHealing.gif", "Each time you cleanse a Totem, Inner Healing activates: You are automatically healed 1 Health State when hiding inside a Locker for 10/9/8 seconds while injured or suffering from the Deep Wound Status Effect. Inner Healing does not activate if you currently suffer from the Broken Status Effect.")
const ironWill = new Perk("Iron Will", "survivorimgs/IronWill.gif", "When injured, Grunts of Pain are reduced by 50/75/100 %.")
const Kindred = new Perk("Kindred", "survivorimgs/Kindred.gif", "While you are hooked: The Auras of all Survivors are revealed to one another. Whenever the Killer is within 8/12/16 metres of your Hook, their Aura is revealed to all Survivors. While another Survivor is hooked: The Auras of all other Survivors are revealed to you. Whenever the Killer is within 8/12/16 metres of the hooked Survivor, their Aura is revealed to you.")
const Kinship = new Perk("Kinship", "survivorimgs/Camaraderie.gif", "While you are on the Hook in the Struggle Phase, Kinship activates: If another Survivor is within 16 metres of your Hook while Kinship is active, the Struggle Phase timer is paused for 26/30/34 seconds.")
const Leader = new Perk("Leader", "survivorimgs/Leader.gif", "When other Survivors are within 8 metres of you, Leader increases their Action speeds for Healing, Sabotaging, Unhooking, Cleansing, Opening, and Unlocking actions by 15/20/25 %. This effect lingers for 15 seconds when leaving Leader's range. Leader does not stack with other instances of itself.")
const leftBehind = new Perk("Left Behind", "survivorimgs/LeftBehind.gif", "When you are the last Survivor remaining in the Trial, the Aura of the Hatch is revealed to you when you are within 24/28/32 metres.")
const Lightweight = new Perk("Lightweight", "survivorimgs/Lightweight.gif", "Your Scratch Marks start to disappear 1/2/3 seconds sooner.")
const Lithe = new Perk("Lithe", "survivorimgs/Lithe.gif", "After performing a rushed vault, break into a sprint of 150 % of your normal running speed for a maximum of 3 seconds. Lithe causes the Exhausted Status Effect for 60/50/40 seconds. Lithe cannot be used when Exhausted.")
const luckyBreak = new Perk("Lucky Break", "survivorimgs/LuckyBreak.gif", "Whenever you are in the Injured State, Lucky Break activates: Bleeding and Scratch Marks are suppressed for a maximum of 140/50/60 seconds, after which Lucky Break is disabled for the remainer of the Trial. Lucky Break deactivates when you are Healthy or in the Dying State.")
const mettleOfMan = new Perk("Mettle of Man", "survivorimgs/MettleOfMan.gif", "After triggering your third Protection Hit, Mettle of Man activates and you are protected by the Endurance Status Effect: Any damage taken that would put you into the Dying State from the Injured State is blocked. When you are healed again, your Aura will be revealed to the Killer whenever you are farther than 12/14/16 metres away. Mettle of Man deactivates the next time you are put into the Dying State. Increases the odds of being the Obsession by 100 %.")
const noMither = new Perk("No Mither", "survivorimgs/NoMither.gif", "You suffer from the Broken Status Effect for the entire Trial, but benefit from the following effects: Pools of Blood are suppressed. When injured or dying, Grunts of Pain are reduced by 25/50/75 %. Your Recovery speed is increased by 15/20/25 %. You can recover fully from the Dying State.")
const noOneLeftBehind = new Perk("No One Left Behind", "survivorimgs/NoOneLeftBehind.gif", "Once at least one Exit Gate has been opened, No One Left Behind activates: Gain a 50/75/100 % Action Speed Bonus to Unhooking and Healing other Survivors. The Auras of all other Survivors are revealed to you. No One Left Behind grants 30/40/50 % bonus Bloodpoints for actions in the Altruism Category.")
const objectOfObsession = new Perk("Object of Obsession", "survivorimgs/ObjectOfObsession.gif", "Whenever the Killer reads your Aura, Object of Obsession activates: The Killer's Aura is revealed to you for the same duration as they read your Aura. Your Action speeds in Repairing, Healing, and Cleansing are increased by 2/4/6 %. If you are the Obsession, your Aura is revealed to the Killer for 3 seconds every 30 seconds. Increases the odds of being the Obsession by 100 %.")
const offTheRecord = new Perk("Off the Record", "survivorimgs/OffTheRecord.gif", "After being unhooked or unhooking yourself, Off the Record activates for the next 60/70/80 seconds: Your Aura will not be shown to the Killer if they attempt to read it. When injured, Grunts of Pain are reduced by 100 %.")
const openHanded = new Perk("Open-Handed", "survivorimgs/Open-Handed.gif", "Strengthens the potential in your and your team's Aura-reading abilities. Open-Handed increases all Aura-reading ranges by 8/12/16 metres. Open-Handed does not stack with other instances of itself.")
const Pharmacy = new Perk("Pharmacy", "survivorimgs/Pharmacy.gif", "You have a knack for finding medicine. Unlocking Chests is 40/60/80 % faster. Unlocking your first Chest guarantees an Emergency Med-Kit. Pharmacy reduces the audible range of your Chest-unlocking noises by 8 metres.")
const plunderersInstinct = new Perk("Plunderer's Instinct", "survivorimgs/PlunderersInstinct.gif", "Unlocks potential in your Aura-reading ability. The Auras of closed Chests and dropped Items throughout the Trial Grounds are revealed to you within 16/24/32 metres. Grants a considerably better chance at finding an Item of a higher Rarity from Chests.")
const Poised = new Perk("Poised", "survivorimgs/Poised.gif", "After a Generator is completed, you will not leave any Scratch Marks for the next 6/8/10 seconds.")
const powerStruggle = new Perk("Power Struggle", "survivorimgs/PowerStruggle.gif", "While being carried by The Killer, reaching 35/30/25 % Wiggling progression activates Power Struggle: You can drop a nearby, standing Pallet to stun the Killer and escape their grasp. Power Struggle deactivates after triggering successfully.")
const Premonition = new Perk("Premonition", "survivorimgs/Premonition.gif", "Get an auditory warning when looking in the Killer's direction within a 45 ° cone within 36 metres. Premonition has a cool-down of 60/45/30 seconds each time it activates.")
const proveThyself = new Perk("Prove Thyself", "survivorimgs/ProveThyself.gif", "Gain a stack-able 15 % repair Speed bonus for each Survivor within 4 metres of you, up to a maximum of 45 %. This effect is also apllied to all other Survivors within that range. Prove Thyself grants 50/75/100 % bonus Bloodpoints for Co-operative actions. Prove Thyself does not stack with other instances of itself.")
const quickQuiet = new Perk("Quick & Quiet", "survivorimgs/QuickAndQuiet.gif", "Loud Noise Notifications for rushing to vault Windows, or to enter or exit Lockers are completely suppressed. Quick & Quiet has a cool-down of 30/25/20 seconds.")
const redHerring = new Perk("Red Herring", "survivorimgs/RedHerring.gif", "After repairing a Generator for at least 3 seconds, its Aura is highlighted to you in yellow. The Generator stays highlighted until it is either fully repaired, you start repairing another Generator, or enter a Locker. Entering a Locker will trigger a Loud Noise Notification for the Killer at the highlighted Generator's location. Red Herring has a cool-down of 60/50/40 seconds.")
const Renewal = new Perk("Renewal", "survivorimgs/Renewal.gif", "When you heal another Survivor for the equivalent of 1 Health State, Renewal activates: The next time you are unhooked or unhook yourself, you suffer from the Broken Status Effect until Renewal deactivates. You are automatically healed 1 Health State after 28/24/20 seconds. While Renewal is active, the following conditions will deactivate it: Successfully being healed by Renewal. Being put into the Dying State before the timer elapses. Renewal does not activate if you already suffer from the Broken Status Effect.")
const repressedAlliance = new Perk("Repressed Alliance", "survivorimgs/RepressedAlliance.gif", "After repairing Generators for a total of 55/50/45 seconds, Repressed Alliance activates: Press the Active Ability button to call upon The Entity to block the Generator you are currently repairing for 30 seconds, after which Repressed Alliance deactivates. The Aura of the blocked Generator is revealed to all Survivors in white.")
const Resilience = new Perk("Resilience", "survivorimgs/Resilience.gif", "When injured, your Action speeds in Repairing, Healing, Sabotaging, Unhooking, Vaulting, Cleansing, Opening, and Unlocking are increased by 3/6/9 %.")
const Resurgence = new Perk("Resurgence", "survivorimgs/Teachable_resurgence.png", "After being unhooked or unhooking yourself, instantly gain 40/45/50 % to your Healing progress.")
const rookieSpirit = new Perk("Rookie Spirit", "survivorimgs/Teachable_rookieSpirit.png", "While repairing Generators, complete 5/4/3 Good or Great Skill Checks to activate Rookie Spirit for the remainder of the Trial: Once active, the Auras of any regressing Generators are revealed to you.")
const Saboteur = new Perk("Saboteur", "survivorimgs/Teachable_saboteur.png", "Unlocks potential in your Aura-reading ability. While a Survivor is being carried, the Auras of all Hooks within 56 metres of the location they were picked up at are revealed to you. Unlocks the ability to sabotage Hooks without needing a Toolbox IconItems toolbox.png: Sabotaging a Hook without a Toolbox takes 3 seconds. The Sabotage action has a cool-down of 90/75/60 seconds.")
const selfCare = new Perk("Self-Care", "survivorimgs/Self-Care.gif", "	Unlocks the ability to heal yourself without needing a Med-Kit IconItems firstAidKit.png at 50 % of the normal Healing speed. When using a Med-Kit IconItems firstAidKit.png, its Depletion rate is decreased by 10/15/20 %.")
const selfPreservation = new Perk("Self-Preservation", "survivorimgs/Teachable_self-Preservation.png", "Whenever another Survivor is hit with a Basic Attack or Special Attack within 16 metres of you, Self-Preservation activates: Scratch Marks, Grunts of Pain when injured, and Bleeding are suppressed for the next 6/8/10 seconds.")
const slipperyMeat = new Perk("Slippery Meat", "survivorimgs/SlipperyMeat.gif", "You have developed an efficent way to get off Hooks. Grants 3 additional Self-Unhook attempts. Your Self-Unhook chance is increased by 2/3/4 %.")
const smallGame = new Perk("Small Game", "survivorimgs/SmallGame.gif", "Get an auditory warning when looking in the direction of Totems in a 45 ° cone within 8/10/12 metres. Small Game has a cool-down of 14/12/10 seconds each time it activates. For each Dull or Hex Totem cleansed by any Player, Small Game gains 1 Token: Each Token decreases the Detection cone's angle by 5 °, down to a minimum of 20 °.")
const smashHit = new Perk("Smash Hit", "survivorimgs/Teachable_smashHit.png", "After stunning the Killer with a Pallet, break into a sprint at 150 % of your normal running speed for a maximum of 4 seconds. Smash Hit causes the Exhausted Status Effect for 60/50/40 seconds. Smash Hit cannot be used when Exhausted.")
const soleSurvivor = new Perk("Sole Survivor", "survivorimgs/Teachable_soleSurvivor.png", "Survivor gains 1 Token, up to a maximum of 3 Tokens: Each Token grants a stack-able radius of 20/22/24 metres within which the Killer is unable to read your Aura, up to a maximum of 60/66/72 metres. Increases the odds of being the Obsession by 100 %. The Killer can only be obsessed with one Survivor at a time.")
const Solidarity = new Perk("Solidarity", "survivorimgs/Teachable_solidarity.png", "When injured, healing another Survivor without using a Med-Kit IconItems firstAidKit.png also heals you with a Conversion rate of 40/45/50 %.")
const soulGuard = new Perk("Soul Guard", "survivorimgs/Teachable_soulGuard.png", "After being healed from or having recovered from the Dying State, Soul Guard grants you the Endurance Status Effect for the next 4/6/8 seconds. Any damage taken that would put you into the Dying State will instead trigger the Deep Wound Status Effect, after which you have 20 seconds to Mend yourself. Taking any damage while under the effect of Deep Wound or if its timer runs out will put you into the Dying State. Soul Guard allows you to completely recover from the Dying State when you are affected by the Cursed Status Effect.Soul Guard has a cool-down of 30 seconds.")
const spineChill = new Perk("Spine Chill", "survivorimgs/SpineChill.gif", "Whenever the Killer is looking in your direction when within 36 metres of you, Spine Chill activates: Skill Check Trigger odds are increased by 10 %. Skill Check Success zones are reduced by 10 %. Your Action speeds in Repairing, Healing, Sabotaging, Unhooking, Vaulti")
const sprintBurst = new Perk("Sprint Burst", "survivorimgs/Teachable_sprintBurst.png", "	When starting to run, break into a sprint at 150 % of your normal running speed for a maxiumum of 3 seconds. Sprint Burst causes the Exhausted Status Effect for 60/50/40 seconds. Sprint Burst cannot be used when Exhausted.")
const stakeOut = new Perk("Stake Out", "survivorimgs/Teachable_stakeOut.png", "Getting close to the Killer fills you with determination. Every 15 seconds you are standing within the Killer's Terror Radius without being chased, Stake Out gains 1 Token, up to a maximum of 2/3/4 Tokens. When Stake Out has at least 1 Token, Good Skill Checks consume 1 Token and are considered Great Skill Checks, granting an additional Progression bonus of 1 %. Great Skill Checks do not consume any Tokens.")
const Streetwise = new Perk("Streetwise", "survivorimgs/Teachable_streetwise.png", "The Depletion rate of your Items is reduced by 15/20/25 %. This effect also applies to all other Survivors within 8 metres of you and lingers for 15 seconds.")
const Technician = new Perk("Technician", "survivorimgs/Teachable_technician.png", "Failing a Skill Check while repairing: Prevents the Generator Explosion. Applies the default Regression penalty. Applies an additional Regression penalty of 5/4/3 %. Technician reduces the audible range of your Generator-repairing noises by 8 metres.")
const Tenacity = new Perk("Tenacity", "survivorimgs/Teachable_tenacity.png", "Your ferocious tenacity in dire situations allows you to crawl 30/40/50 % faster and also recover at the same time.")
const thisIsNotHappening = new Perk("This is Not Happening", "survivorimgs/ThisIsNotHappening.gif", "When injured, the Success zone of Great Skill Checks while Repairing, Healing, and Sabotaging is increased by 10/20/30 %.")
const Unbreakable = new Perk("Unbreakable", "survivorimgs/Teachable_unbreakable.png", "Once per Trial, you can completely recover from the Dying State. Your Recovery speed is increased by 25/30/35 %.")
const upTheAnte = new Perk("Up the Ante", "survivorimgs/Teachable_upTheAnte.png", "For Each Survivor still in the Trial, Up the Ante gains 1 Token. Each Token applies a stack-able 1/2/3 % bonus to the Luck of all Survivors, up to a maximum of 3/6/9 %.")
const urbanEvasion = new Perk("Urban Evasion", "survivorimgs/Teachable_urbanEvasion.png", "When crouching, your Movement Speed is increased by 90/95/100 %.")
const Vigil = new Perk("Vigil", "survivorimgs/Teachable_vigil.png", "You recover 20/25/30 % faster from the Blindness, Broken, Exhaustion, Exposed, Haemorrhage, Hindered, and Oblivious Status Effects. This effect also applies to all other Survivors within 8 metres of you and lingers for 15 seconds.")
const Visionary = new Perk("Visonary", "survivorimgs/Teachable_visionary.png", "The Auras of Generators are revealed to you within 32 metres. Each time a Generator is completed, Visionary is disabled for 20/18/16 seconds.")
const wakeUp = new Perk("Wake Up!", "survivorimgs/Teachable_wakeUp.png", "Once all Generators are completed, Wake Up! activates: The Auras of the Exit Gate Switches are revealed to you within 128 metres. When opening an Exit Gate, your Aura is revealed to all other Survivors within 128 metres. You open Exit Gates 5/10/15 % faster.")
const wellMakeIt = new Perk("We'll Make It", "survivorimgs/WellMakeIt.gif", "Whenever you rescue a Survivor from a Hook, your Altruistic Healing speed is increased by 100 % for the next 30/60/90 seconds.")
const wereGonnaLiveForever = new Perk("We're Gonna Live Forever", "survivorimgs/Teachable_wereGonnaLiveForever.png", "Performing any of the following actions has We're Gonna Live Forever gain 1 Token: Performing a Safe Hook Rescue Taking a Protection Hit for an injured Survivor. Stunning or Blinding the Killer to rescue a carried Survivor Each Token grants a stack-able 25 % bonus to all Bloodpoint gains, up to a maximum of 50/75/100 %. The bonus Bloodpoints are only awarded post-Trial.")
const windowsOfOpportunity = new Perk("Windows of Opportunity", "survivorimgs/Teachable_windowsOfOpportunity.png", "The Auras of Breakable Walls, Pallets, and Windows are revealed to you within 24/28/32 seconds.")

const perks = [aceInTheHole, Adrenaline, Aftercare, Alert, anyMeansNecessary, Appraisal, Autodidact, Babysitter, balancedLanding, situationalAwareness, biteTheBullet, blastMine, bloodPact, boilOver, Bond, boonCircleofHealing, boonShadowStep, borrowedTime, botanyKnowledge, Breakdown, buckleUp, builtToLast, calmSpirit, Clairvoyance, Counterforce, danceWithMe, darkSense, deadHard, Deception, decisiveStrike, Deliverance, desperateMeasures, detectivesHunch, Distortion, Diversion, dejaVu, Empathy, fastTrack, selfAware, Flashbang, flipFlop, forThePeople, Guardian, headOn, Hope, innerHealing, ironWill, Kindred, Kinship, Leader, leftBehind, Lightweight, Lithe, luckyBreak, mettleOfMan, noMither, noOneLeftBehind, objectOfObsession, offTheRecord, openHanded, Pharmacy, plunderersInstinct, Poised, powerStruggle, Premonition, proveThyself, quickQuiet, redHerring, Renewal, repressedAlliance, Resilience, Resurgence, rookieSpirit, Saboteur, selfCare, selfPreservation, slipperyMeat, smallGame, smashHit, soleSurvivor, Solidarity, soulGuard, spineChill, sprintBurst, stakeOut, Streetwise, Technician, Tenacity, thisIsNotHappening, Unbreakable, upTheAnte, urbanEvasion, Vigil, Visionary, wakeUp, wellMakeIt, wereGonnaLiveForever, windowsOfOpportunity]
const dice = document.getElementById('dice')
const pSelf = document.getElementById("self-destro")
const p1 = document.getElementById('p1s')
const p2 = document.getElementById('p2s')
const p3 = document.getElementById('p3s')
const p4 = document.getElementById('p4s')

dice.addEventListener('click', () => {
    pSelf.innerHTML = ''
    randomPerk(p1)
    randomPerk(p2)
    randomPerk(p3)
    randomPerk(p4)
    perkChecker()
})
function randomPerk(perk) {
    var item = perks[Math.floor(Math.random()*perks.length)];
    perk.innerHTML = `
    <div class="perk-tip">
    <img
      class="mainimgs"
      id="perk-imgs"
      src="${item.image}"
    />
    <div class="perk-info">
      <h1 class="title" id="perk-title">${item.title}</h1>
      <p>${item.desc}</p>
    </div>
  </div>
</div>`
}
function perkChecker(){
    const perkOneTitle = p1.childNodes[1].childNodes[3].childNodes[1].textContent
    const perkTwoTitle = p2.childNodes[1].childNodes[3].childNodes[1].textContent
    const perkThreeTitle = p3.childNodes[1].childNodes[3].childNodes[1].textContent
    const perkFourTitle = p4.childNodes[1].childNodes[3].childNodes[1].textContent
    // console.log(perkOneTitle)
    // console.log(perkTwoTitle)
    if(perkOneTitle === perkTwoTitle){
        randomPerk(p1) 
        randomPerk(p2) 
        console.log("same title")}
    if(perkOneTitle === perkThreeTitle) {
        randomPerk(p1)
        randomPerk(p3)
    }
    if(perkOneTitle === perkFourTitle) {
        randomPerk(p1)
        randomPerk(p4)
    }
    if(perkTwoTitle === perkThreeTitle) {
        randomPerk(p2)
        randomPerk(p3)
    }
    if(perkTwoTitle === perkFourTitle) {
        randomPerk(p2)
        randomPerk(p4)
    }
    if(perkThreeTitle === perkFourTitle) {
        randomPerk(p3)
        randomPerk(p4)
    }
    
}